// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "targetLanguage": string;
      "downloadComparison": boolean;
      "downloadMarkdown": boolean;
      "confirmBeforeSubmit": boolean;
      "serverURL": string;
      "pendingJobs": string;
      "firstRunNoticeShown": boolean;
    };
  }
}
